# Generated by Django 4.2.4 on 2023-10-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
